name: No Fixups
permissions:
  contents: read

on: pull_request

jobs:
  no-fixups:
    runs-on: ubuntu-latest
    steps:
      - uses: matijs/no-fixups-action@8dfcf79304e29c3aa37e327cfc1d3685dca3c6c0 # v1.1.4
